# `foreach` 方法跳出循环

通常，在 `for`循环中跳出循环可以用 `break` 或者 `continue` 来跳出循环。
- `break`：跳出循环；
- `continue`：跳过当次循环。
- `return`：语句仅可用在函数内(非函数内使用会直接报语法错)，是用来终止函数的执行，并返回一个指定的值给函数调用者。

而有时候需要在 `foreach` 中跳出循环，该怎么做呢？

> `forEach()` 方法用于调用数组的每个元素，并将元素传递给回调函数。对于空数组不会执行回调函数。
> 回调函数的参数 ：
>
> - `function(currentValue, index, arr)`
> - `currentValue` 必需。当前元素
> - `index` 可选。当前元素的索引值
> - `arr` 可选。当前元素所属的数组对象

## 在 `forEach` 中使用return：

```js
let arr = [1, 2, 3, 4, 5, 6, 7, 8, 9];
let num = 6
arr.forEach((item) => {
    if (item == num) {
        return;
    }
    console.log('item', item);
})
console.log(123)
```

> 运行结果
>
> ```
> item 1
> item 2
> item 3
> item 4
> item 5
> item 7
> item 8
> item 9
> 123
> ```

可以看到，`forEach`中使用 `return` 语句的作用只能跳出当前循环（实现了`continue`的效果），并不能跳出整个循环，没达到期待的效果，满足条件后还继续执行了循环。

## 在 `forEach` 中使用break：

```js
let arr = [1, 2, 3, 4, 5, 6, 7, 8, 9];
let num = 6
arr.forEach((item) => {
    if (item == num) {
        break;
    }
    console.log('item', item);
})
console.log(123)
```

直接报错了，后面的代码也没执行。

## 在 `forEach` 中使用continue：

```js
let arr = [1, 2, 3, 4, 5, 6, 7, 8, 9];
let num = 6
arr.forEach((item) => {
    if (item == num) {
        continue;
    }
    console.log('item', item);
})
console.log(123)
```

和 break 一样，直接报错了，后面的代码也没执行。

### 上面的例子可以看到，`foreach`不能使用`break`和`continue`这两个关键字。

因为 `forEach` 本身无法跳出循环，必须遍历所有的数据才能结束，它传入的是一个回调函数，因此形成了一个作用域，它内部所定义的变量不会像for循环一样污染全局变量。

## 解决方法

`forEach`方法跳出循环 —— 通过 `try catch` 抛出异常的方式跳出循环

```js
let arr = [1, 2, 3, 4, 5, 6, 7, 8, 9];
let num = 6
try {
    arr.forEach((item, i) => {
        console.log('item', item)
        if (item === num) {
            throw new Error('LoopInterrupt'); // 满足条件，跳出循环
        }
    })
} catch (e) {
    if (e.message !== "LoopInterrupt") throw e
}
console.log(123)
```

> 运行效果：
>
> ```js
> item 1
> item 2
> item 3
> item 4
> item 5
> item 6
> 123
> ```